name: Docker Build (Fast - AMD64 Only)

# Fast build workflow for development/testing
# Only builds linux/amd64 platform (~6-8 min vs ~15 min)
# Use for quick iteration and testing

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for the image (default: dev)'
        required: false
        default: 'dev'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-fast:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ github.event.inputs.tag || 'dev' }}
            type=sha,prefix=dev-

      - name: Build and push Docker image (AMD64 only)
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          # ONLY amd64 for speed
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # Use aggressive caching
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # Skip provenance/sbom for speed
          provenance: false
          sbom: false

      - name: Image built successfully
        run: |
          echo "::notice::Fast build complete! Image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.tag || 'dev' }}"
          echo "::notice::Pull with: docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.tag || 'dev' }}"
          echo "::notice::Build time: ~6-8 minutes (vs ~15 min for multi-platform)"
