name: Go
on:
  push:
  pull_request:
  schedule:
    # Run every 12 hours, at the 15 minute mark. E.g.
    # 2020-11-29 00:15:00 UTC, 2020-11-29 12:15:00 UTC, 2020-11-30 00:15:00 UTC
    - cron:  '15 */12 * * *'

permissions:
  contents: read

jobs:

  build:
    name: Build and Unit Test
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Check out code
        uses: actions/checkout@v5

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v -race -covermode=atomic -coverprofile=coverage.out ./...

      - name: Upload Coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverage.out
